/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;


import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author tonyo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    public Inicio() {
        initComponents();
        setTitle("Timbiriche");
       
        
        setLocationRelativeTo(null);
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanelInicioImagen = new Panel.PanelGambar(0);
        btnAvatar1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        txtFldNombre = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        btnAvatar2 = new javax.swing.JButton();
        jPanelAvatar1 = new javax.swing.JPanel();
        jPanelAvatarr2 = new javax.swing.JPanel();
        btnAvatar3 = new javax.swing.JButton();
        jPanelAvatarr3 = new javax.swing.JPanel();
        btnAvatar4 = new javax.swing.JButton();
        jPanelAvatarr4 = new javax.swing.JPanel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInicioImagen.setRequestFocusEnabled(false);
        jPanelInicioImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MonkyIcon.jpg"))); // NOI18N
        btnAvatar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatar1ActionPerformed(evt);
            }
        });
        jPanelInicioImagen.add(btnAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 80, 80));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 51));
        txtNombre.setText("Nombre");
        jPanelInicioImagen.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, 30));

        txtFldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNombreActionPerformed(evt);
            }
        });
        jPanelInicioImagen.add(txtFldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 130, 30));

        btnIniciar.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanelInicioImagen.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 120, 50));

        btnAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xboxAvatarBeanieNUVO.png"))); // NOI18N
        btnAvatar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatar2ActionPerformed(evt);
            }
        });
        jPanelInicioImagen.add(btnAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 80, 80));

        jPanelAvatar1.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanelAvatar1Layout = new javax.swing.GroupLayout(jPanelAvatar1);
        jPanelAvatar1.setLayout(jPanelAvatar1Layout);
        jPanelAvatar1Layout.setHorizontalGroup(
            jPanelAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAvatar1Layout.setVerticalGroup(
            jPanelAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelInicioImagen.add(jPanelAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jPanelAvatarr2.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanelAvatarr2Layout = new javax.swing.GroupLayout(jPanelAvatarr2);
        jPanelAvatarr2.setLayout(jPanelAvatarr2Layout);
        jPanelAvatarr2Layout.setHorizontalGroup(
            jPanelAvatarr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAvatarr2Layout.setVerticalGroup(
            jPanelAvatarr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelInicioImagen.add(jPanelAvatarr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        btnAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SmileyIcon.jpg"))); // NOI18N
        btnAvatar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatar3ActionPerformed(evt);
            }
        });
        jPanelInicioImagen.add(btnAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, 80));

        jPanelAvatarr3.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanelAvatarr3Layout = new javax.swing.GroupLayout(jPanelAvatarr3);
        jPanelAvatarr3.setLayout(jPanelAvatarr3Layout);
        jPanelAvatarr3Layout.setHorizontalGroup(
            jPanelAvatarr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAvatarr3Layout.setVerticalGroup(
            jPanelAvatarr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelInicioImagen.add(jPanelAvatarr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        btnAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pandaIcon.jpg"))); // NOI18N
        btnAvatar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatar4ActionPerformed(evt);
            }
        });
        jPanelInicioImagen.add(btnAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 80, 80));

        jPanelAvatarr4.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanelAvatarr4Layout = new javax.swing.GroupLayout(jPanelAvatarr4);
        jPanelAvatarr4.setLayout(jPanelAvatarr4Layout);
        jPanelAvatarr4Layout.setHorizontalGroup(
            jPanelAvatarr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAvatarr4Layout.setVerticalGroup(
            jPanelAvatarr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelInicioImagen.add(jPanelAvatarr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        getContentPane().add(jPanelInicioImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 710, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNombreActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        
        String[] options = new String[] {"Crear", "Unirme", "Cancelar"};
        int response = JOptionPane.showOptionDialog(null, "Desea crear o unirse a partida", "Iniciar",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        if(response==0){
            MenuParaCrearPartida mp = new MenuParaCrearPartida();
            
            
            
//            JComboBox combo1 = new JComboBox();
//            
//            combo1.addItem("1");
//            combo1.addItem("2");
//            combo1.addItem("3");
//            combo1.addItem("4");
//            
//            JPopupMenu.
//            JPopupMenu.add(combo1);
            
           
            
            dispose();

            mp.setVisible(true);
            
        }
        if(response==1){
            dispose();
            Unir_Partida up = new Unir_Partida();
           
            up.setVisible(true);
        }
        if(response==3){
            dispose();
        }
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnAvatar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatar1ActionPerformed
        // TODO add your handling code here:
        
        if(!btnAvatar2.isSelected() || !btnAvatar3.isSelected() || !btnAvatar4.isSelected()){
           jPanelAvatarr4.setBackground(Color.DARK_GRAY);
            jPanelAvatarr3.setBackground(Color.DARK_GRAY);
            jPanelAvatarr2.setBackground(Color.DARK_GRAY);
             jPanelAvatar1.setBackground(Color.yellow);
           
        }
       
            btnAvatar2.updateUI();
            btnAvatar3.updateUI();
            btnAvatar4.updateUI();
    }//GEN-LAST:event_btnAvatar1ActionPerformed

    private void btnAvatar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatar2ActionPerformed
        // TODO add your handling code here:
        if(!btnAvatar1.isSelected() || !btnAvatar3.isSelected() || !btnAvatar4.isSelected()){
            jPanelAvatarr4.setBackground(Color.DARK_GRAY);
            jPanelAvatarr3.setBackground(Color.DARK_GRAY);
            jPanelAvatar1.setBackground(Color.DARK_GRAY);
            jPanelAvatarr2.setBackground(Color.yellow);
            
           
        }
         btnAvatar1.updateUI();
     
            btnAvatar3.updateUI();
            btnAvatar4.updateUI();
           
    }//GEN-LAST:event_btnAvatar2ActionPerformed

    private void btnAvatar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatar3ActionPerformed
        // TODO add your handling code here:
        
        if(!btnAvatar1.isSelected() || !btnAvatar2.isSelected() || !btnAvatar4.isSelected()){
            jPanelAvatarr4.setBackground(Color.DARK_GRAY);
            jPanelAvatar1.setBackground(Color.DARK_GRAY);
            jPanelAvatarr2.setBackground(Color.DARK_GRAY);
            jPanelAvatarr3.setBackground(Color.yellow);
            
           
        }
         btnAvatar1.updateUI();
         btnAvatar2.updateUI();
           
            btnAvatar4.updateUI();
           
    }//GEN-LAST:event_btnAvatar3ActionPerformed

    private void btnAvatar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatar4ActionPerformed
        // TODO add your handling code here:
        
        
        if(!btnAvatar1.isSelected() || !btnAvatar3.isSelected() || !btnAvatar2.isSelected()){
            jPanelAvatarr4.setBackground(Color.yellow);
            jPanelAvatarr3.setBackground(Color.DARK_GRAY);
            jPanelAvatar1.setBackground(Color.DARK_GRAY);
            jPanelAvatarr2.setBackground(Color.DARK_GRAY);
            
           
        }
         btnAvatar1.updateUI();
         btnAvatar2.updateUI();
            btnAvatar3.updateUI();
        
           
    }//GEN-LAST:event_btnAvatar4ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvatar1;
    private javax.swing.JButton btnAvatar2;
    private javax.swing.JButton btnAvatar3;
    private javax.swing.JButton btnAvatar4;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel jPanelAvatar1;
    private javax.swing.JPanel jPanelAvatarr2;
    private javax.swing.JPanel jPanelAvatarr3;
    private javax.swing.JPanel jPanelAvatarr4;
    private javax.swing.JPanel jPanelInicioImagen;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField txtFldNombre;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
